export const dlcNegativaProteinasDefaultProducts = [
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Carne Vaca" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Carne Frango" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Carne Peixe" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Ovo" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Bacon" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Frango Grelhado" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Frango Crispy" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Nuggets" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Filetes de Peixe" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Camarão" },
  // Novos produtos adicionados
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Carne Reg" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Carne Royal" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Chk Nuggets" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Chk OPT" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Chk Mythic" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Chk Delight" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Veggie" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Chk Wings" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Bacon Long" },
  { category: "DLC NEGATIVA PROTEÍNAS", name: "Carne Bifana" },
];